### ISSUE TITLE
Exclusion list does not appear

### ISSUE THREAD

**Issue by AleytiaFairlight** [FFDA/revanced-cli-gui#1]
Wheck ticking the checkbox for exclusion the lost of patches that we can exclude does not appear.

![image](https://github.com/user-attachments/assets/ea822d50-8cb1-48b6-915f-a99bf82d3c78)

![image](https://github.com/user-attachments/assets/b3bf0eb6-d94c-449e-ad8b-9cdd6e965afe)

Running v1.4.0

**Comment by FFDA** [comment]
Hi, thanks for the bug report. However, at least on my linux install I can't reproduce the bug. The only way I can make exclude and include tabs not to show any patches is to have nothing selected (or wrong file like *.txt) in "Youtube APK", "Revanced CLI" or "Revanced patches" fields.
![image](https://github.com/user-attachments/assets/59c41f5b-7ca8-4d9a-ae89-1892fd4fc604)
Could you check if you definitely have something selected in these fields? If so tell me which you are using. It will be easier to reproduce the bug for me. 
Moreover, "Revanced integrations" are not important to list the patches, but it is still necessary for the patches to work correctly.

**Comment by AleytiaFairlight** [comment]
Interesting, so if I just open the app and then have the latest versions automatically selected that does not count? I have to manually reselect them all before the exclusion list populates?

**Comment by FFDA** [comment]
No, that should be enough. I just tried, and it worked that way on my computer. So, did changing the options (or reselecting the same ones) solve the problem? And are you 100% sure that all of the selected dependencies were the latest versions? I once had a problem where one of the comboboxes would automatically select an older version of the dependencies, and while include/exclude would show the options, the resulting APK would crash at app start.

I think I need to add an option in the settings to print the commands the program uses to patch and retrieve other data. This would allow me to debug these issues more easily. I just hadn’t actually considered that someone would be using this.

**Comment by AleytiaFairlight** [comment]
well it's a good program and it's a friend of mine using it rather than me. Yes I have the right dependencies alonbgside the right CLI version. the problem occurs on startup of the app wherein when I start it the latest versions atleast at startup are automatically selected. ticking the box that would show the exclusion list does not display the exclusions


https://github.com/user-attachments/assets/0d0c4acb-1e5a-4d48-959e-aa96b671aa22

**Comment by FFDA** [comment]
Thank you for the video. It helped me figure out the problem. They changed the API again, or more precisely, they are planning to change it with the revanced-cli v5.x.x. Most likely, the changes will be made in [this release](https://github.com/ReVanced/revanced-cli/releases/tag/v5.0.0-dev.2). They did this once before with the release of v4.x.x.

I will make the necessary changes and do a release once they release the stable version of revanced-cli v5.x.x. In the meantime, you can use the stable version, or they have their own android app for patching APK files.
